import { BinSanalPos } from "../definitions/BinSanalPos";
import { BinSanalPosResponse } from "../definitions/BinSanalPosResponse";
import { BinSanalPos2 } from "../definitions/BinSanalPos2";
import { BinSanalPos2Response } from "../definitions/BinSanalPos2Response";
import { TpOzelOranListe } from "../definitions/TpOzelOranListe";
import { TpOzelOranListeResponse } from "../definitions/TpOzelOranListeResponse";
import { TpOzelOranSkListe } from "../definitions/TpOzelOranSkListe";
import { TpOzelOranSkListeResponse } from "../definitions/TpOzelOranSkListeResponse";
import { TpOzelOranSkGuncelle } from "../definitions/TpOzelOranSkGuncelle";
import { TpOzelOranSkGuncelleResponse } from "../definitions/TpOzelOranSkGuncelleResponse";
import { TpIslemDekontGonder } from "../definitions/TpIslemDekontGonder";
import { TpIslemDekontGonderResponse } from "../definitions/TpIslemDekontGonderResponse";
import { TpIslemOdeme } from "../definitions/TpIslemOdeme";
import { TpIslemOdemeResponse } from "../definitions/TpIslemOdemeResponse";
import { TpWmdPay } from "../definitions/TpWmdPay";
import { TpWmdPayResponse } from "../definitions/TpWmdPayResponse";
import { TpWmdUcdV2 } from "../definitions/TpWmdUcdV2";
import { TpWmdUcdV2Response } from "../definitions/TpWmdUcdV2Response";
import { TpWmdUcd } from "../definitions/TpWmdUcd";
import { TpWmdUcdResponse } from "../definitions/TpWmdUcdResponse";
import { TpWmdUcdWp } from "../definitions/TpWmdUcdWp";
import { TpWmdUcdWpResponse } from "../definitions/TpWmdUcdWpResponse";
import { TpWmdUcdPuan } from "../definitions/TpWmdUcdPuan";
import { TpWmdUcdPuanResponse } from "../definitions/TpWmdUcdPuanResponse";
import { PaymentHopi } from "../definitions/PaymentHopi";
import { PaymentHopiResponse } from "../definitions/PaymentHopiResponse";
import { TpMultiplePayment } from "../definitions/TpMultiplePayment";
import { TpMultiplePaymentResponse } from "../definitions/TpMultiplePaymentResponse";
import { TpMultiplePaymentStatus } from "../definitions/TpMultiplePaymentStatus";
import { TpMultiplePaymentStatusResponse } from "../definitions/TpMultiplePaymentStatusResponse";
import { TpIslemOdemeWns } from "../definitions/TpIslemOdemeWns";
import { TpIslemOdemeWnsResponse } from "../definitions/TpIslemOdemeWnsResponse";
import { TpIslemOdemeWd } from "../definitions/TpIslemOdemeWd";
import { TpIslemOdemeWdResponse } from "../definitions/TpIslemOdemeWdResponse";
import { TpIslemOdemeBkm } from "../definitions/TpIslemOdemeBkm";
import { TpIslemOdemeBkmResponse } from "../definitions/TpIslemOdemeBkmResponse";
import { TpIslemOdemeWks } from "../definitions/TpIslemOdemeWks";
import { TpIslemOdemeWksResponse } from "../definitions/TpIslemOdemeWksResponse";
import { KkSaklama } from "../definitions/KkSaklama";
import { KkSaklamaResponse } from "../definitions/KkSaklamaResponse";
import { KkSakliListe } from "../definitions/KkSakliListe";
import { KkSakliListeResponse } from "../definitions/KkSakliListeResponse";
import { PosOdeme } from "../definitions/PosOdeme";
import { PosOdemeResponse } from "../definitions/PosOdemeResponse";
import { TpIslemSorgulama } from "../definitions/TpIslemSorgulama";
import { TpIslemSorgulamaResponse } from "../definitions/TpIslemSorgulamaResponse";
import { TpIslemSorgulama4 } from "../definitions/TpIslemSorgulama4";
import { TpIslemSorgulama4Response } from "../definitions/TpIslemSorgulama4Response";
import { TpIslemSorgulama5 } from "../definitions/TpIslemSorgulama5";
import { TpIslemSorgulama5Response } from "../definitions/TpIslemSorgulama5Response";
import { TpIslemSorgulama6 } from "../definitions/TpIslemSorgulama6";
import { TpIslemSorgulama6Response } from "../definitions/TpIslemSorgulama6Response";
import { TpIslemSorgulamaWp } from "../definitions/TpIslemSorgulamaWp";
import { TpIslemSorgulamaWpResponse } from "../definitions/TpIslemSorgulamaWpResponse";
import { TpMutabakatDetay } from "../definitions/TpMutabakatDetay";
import { TpMutabakatDetayResponse } from "../definitions/TpMutabakatDetayResponse";
import { TpMutabakatDetay2 } from "../definitions/TpMutabakatDetay2";
import { TpMutabakatDetay2Response } from "../definitions/TpMutabakatDetay2Response";
import { TpMutabakatOzet } from "../definitions/TpMutabakatOzet";
import { TpMutabakatOzetResponse } from "../definitions/TpMutabakatOzetResponse";
import { TpIslemIptalIade } from "../definitions/TpIslemIptalIade";
import { TpIslemIptalIadeResponse } from "../definitions/TpIslemIptalIadeResponse";
import { TpIslemIptalIade2 } from "../definitions/TpIslemIptalIade2";
import { TpIslemIptalIade2Response } from "../definitions/TpIslemIptalIade2Response";
import { TpIslemIzleme } from "../definitions/TpIslemIzleme";
import { TpIslemIzlemeResponse } from "../definitions/TpIslemIzlemeResponse";
import { TpIslemIptalIadeKismi } from "../definitions/TpIslemIptalIadeKismi";
import { TpIslemIptalIadeKismiResponse } from "../definitions/TpIslemIptalIadeKismiResponse";
import { TpIslemIptalIadeKismi2 } from "../definitions/TpIslemIptalIadeKismi2";
import { TpIslemIptalIadeKismi2Response } from "../definitions/TpIslemIptalIadeKismi2Response";
import { TpIslemIptalIadeKismi3 } from "../definitions/TpIslemIptalIadeKismi3";
import { TpIslemIptalIadeKismi3Response } from "../definitions/TpIslemIptalIadeKismi3Response";
import { TpIslemIptalIadeKismi4 } from "../definitions/TpIslemIptalIadeKismi4";
import { TpIslemIptalIadeKismi4Response } from "../definitions/TpIslemIptalIadeKismi4Response";
import { TpIslemIptalIadeKismiWp } from "../definitions/TpIslemIptalIadeKismiWp";
import { TpIslemIptalIadeKismiWpResponse } from "../definitions/TpIslemIptalIadeKismiWpResponse";
import { TpIslemIptalOnProv } from "../definitions/TpIslemIptalOnProv";
import { TpIslemIptalOnProvResponse } from "../definitions/TpIslemIptalOnProvResponse";
import { TpKkVerify } from "../definitions/TpKkVerify";
import { TpKkVerifyResponse } from "../definitions/TpKkVerifyResponse";
import { TpIslemOdemeOnProvKapa } from "../definitions/TpIslemOdemeOnProvKapa";
import { TpIslemOdemeOnProvKapaResponse } from "../definitions/TpIslemOdemeOnProvKapaResponse";
import { TpIslemOdemeOnProv } from "../definitions/TpIslemOdemeOnProv";
import { TpIslemOdemeOnProvResponse } from "../definitions/TpIslemOdemeOnProvResponse";
import { TpIslemOdemeOnProvWmd } from "../definitions/TpIslemOdemeOnProvWmd";
import { TpIslemOdemeOnProvWmdResponse } from "../definitions/TpIslemOdemeOnProvWmdResponse";
import { TpIslemOdemeOnProvWks } from "../definitions/TpIslemOdemeOnProvWks";
import { TpIslemOdemeOnProvWksResponse } from "../definitions/TpIslemOdemeOnProvWksResponse";
import { TpIslemCheckoutSk } from "../definitions/TpIslemCheckoutSk";
import { TpIslemCheckoutSkResponse } from "../definitions/TpIslemCheckoutSkResponse";
import { TpIslemCheckout } from "../definitions/TpIslemCheckout";
import { TpIslemCheckoutResponse } from "../definitions/TpIslemCheckoutResponse";
import { TpIslemCheckoutOdemeWns } from "../definitions/TpIslemCheckoutOdemeWns";
import { TpIslemCheckoutOdemeWnsResponse } from "../definitions/TpIslemCheckoutOdemeWnsResponse";
import { Sha2B64 } from "../definitions/Sha2B64";
import { Sha2B64Response } from "../definitions/Sha2B64Response";
import { VadeliIslemIzleme } from "../definitions/VadeliIslemIzleme";
import { VadeliIslemIzlemeResponse } from "../definitions/VadeliIslemIzlemeResponse";
import { PazaryeriTpAltUyeIsyeriEkleme } from "../definitions/PazaryeriTpAltUyeIsyeriEkleme";
import { PazaryeriTpAltUyeIsyeriEklemeResponse } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeResponse";
import { PazaryeriTpAltUyeIsyeriEklemeV2 } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeV2";
import { PazaryeriTpAltUyeIsyeriEklemeV2Response } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeV2Response";
import { PazaryeriTpAltUyeIsyeriGuncelleme } from "../definitions/PazaryeriTpAltUyeIsyeriGuncelleme";
import { PazaryeriTpAltUyeIsyeriGuncellemeResponse } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeResponse";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2 } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2Response } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2Response";
import { PazaryeriTpAltUyeIsyeriListe } from "../definitions/PazaryeriTpAltUyeIsyeriListe";
import { PazaryeriTpAltUyeIsyeriListeResponse } from "../definitions/PazaryeriTpAltUyeIsyeriListeResponse";
import { PazaryeriTpAltUyeIsyeriSilme } from "../definitions/PazaryeriTpAltUyeIsyeriSilme";
import { PazaryeriTpAltUyeIsyeriSilmeResponse } from "../definitions/PazaryeriTpAltUyeIsyeriSilmeResponse";
import { PazaryeriTpIptalIade } from "../definitions/PazaryeriTpIptalIade";
import { PazaryeriTpIptalIadeResponse } from "../definitions/PazaryeriTpIptalIadeResponse";
import { PazaryeriTpLimitKontrol } from "../definitions/PazaryeriTpLimitKontrol";
import { PazaryeriTpLimitKontrolResponse } from "../definitions/PazaryeriTpLimitKontrolResponse";
import { PazaryeriTpSiparisDetayEkle } from "../definitions/PazaryeriTpSiparisDetayEkle";
import { PazaryeriTpSiparisDetayEkleResponse } from "../definitions/PazaryeriTpSiparisDetayEkleResponse";
import { MpOrderDetailAdd } from "../definitions/MpOrderDetailAdd";
import { MpOrderDetailAddResponse } from "../definitions/MpOrderDetailAddResponse";
import { MpOrderDetailUpdate } from "../definitions/MpOrderDetailUpdate";
import { MpOrderDetailUpdateResponse } from "../definitions/MpOrderDetailUpdateResponse";
import { MpOrderDetailStatus } from "../definitions/MpOrderDetailStatus";
import { MpOrderDetailStatusResponse } from "../definitions/MpOrderDetailStatusResponse";
import { MpOrderDetailQuery } from "../definitions/MpOrderDetailQuery";
import { MpOrderDetailQueryResponse } from "../definitions/MpOrderDetailQueryResponse";
import { MpOrderRefund } from "../definitions/MpOrderRefund";
import { MpOrderRefundResponse } from "../definitions/MpOrderRefundResponse";
import { MpOrderDetailList } from "../definitions/MpOrderDetailList";
import { MpOrderDetailListResponse } from "../definitions/MpOrderDetailListResponse";
import { TpModalPayment } from "../definitions/TpModalPayment";
import { TpModalPaymentResponse } from "../definitions/TpModalPaymentResponse";
import { ParamPazaryeriIslemIzleme } from "../definitions/ParamPazaryeriIslemIzleme";
import { ParamPazaryeriIslemIzlemeResponse } from "../definitions/ParamPazaryeriIslemIzlemeResponse";
import { PazaryeriTpSiparisOnay } from "../definitions/PazaryeriTpSiparisOnay";
import { PazaryeriTpSiparisOnayResponse } from "../definitions/PazaryeriTpSiparisOnayResponse";
import { PazaryeriTpIslemSorgulama } from "../definitions/PazaryeriTpIslemSorgulama";
import { PazaryeriTpIslemSorgulamaResponse } from "../definitions/PazaryeriTpIslemSorgulamaResponse";
import { PosPluginBildirim } from "../definitions/PosPluginBildirim";
import { PosPluginBildirimResponse } from "../definitions/PosPluginBildirimResponse";
import { IlListe } from "../definitions/IlListe";
import { IlListeResponse } from "../definitions/IlListeResponse";
import { MoneyPayIslemSorgulama } from "../definitions/MoneyPayIslemSorgulama";
import { MoneyPayIslemSorgulamaResponse } from "../definitions/MoneyPayIslemSorgulamaResponse";

export interface TurkPosX0020WsX0020TestSoap {
    BIN_SanalPos(bınSanalPos: BinSanalPos, callback: (err: any, result: BinSanalPosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    BIN_SanalPos2(bınSanalPos2: BinSanalPos2, callback: (err: any, result: BinSanalPos2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_Liste(tpOzelOranListe: TpOzelOranListe, callback: (err: any, result: TpOzelOranListeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_SK_Liste(tpOzelOranSkListe: TpOzelOranSkListe, callback: (err: any, result: TpOzelOranSkListeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_SK_Guncelle(tpOzelOranSkGuncelle: TpOzelOranSkGuncelle, callback: (err: any, result: TpOzelOranSkGuncelleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Dekont_Gonder(tpIslemDekontGonder: TpIslemDekontGonder, callback: (err: any, result: TpIslemDekontGonderResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme(tpIslemOdeme: TpIslemOdeme, callback: (err: any, result: TpIslemOdemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_Pay(tpWmdPay: TpWmdPay, callback: (err: any, result: TpWmdPayResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_v2(tpWmdUcdV2: TpWmdUcdV2, callback: (err: any, result: TpWmdUcdV2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD(tpWmdUcd: TpWmdUcd, callback: (err: any, result: TpWmdUcdResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_WP(tpWmdUcdWp: TpWmdUcdWp, callback: (err: any, result: TpWmdUcdWpResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_Puan(tpWmdUcdPuan: TpWmdUcdPuan, callback: (err: any, result: TpWmdUcdPuanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Payment_Hopi(paymentHopi: PaymentHopi, callback: (err: any, result: PaymentHopiResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Multiple_Payment(tpMultiplePayment: TpMultiplePayment, callback: (err: any, result: TpMultiplePaymentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Multiple_Payment_Status(tpMultiplePaymentStatus: TpMultiplePaymentStatus, callback: (err: any, result: TpMultiplePaymentStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WNS(tpIslemOdemeWns: TpIslemOdemeWns, callback: (err: any, result: TpIslemOdemeWnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WD(tpIslemOdemeWd: TpIslemOdemeWd, callback: (err: any, result: TpIslemOdemeWdResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_BKM(tpIslemOdemeBkm: TpIslemOdemeBkm, callback: (err: any, result: TpIslemOdemeBkmResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WKS(tpIslemOdemeWks: TpIslemOdemeWks, callback: (err: any, result: TpIslemOdemeWksResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    KK_Saklama(kkSaklama: KkSaklama, callback: (err: any, result: KkSaklamaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    KK_Sakli_Liste(kkSakliListe: KkSakliListe, callback: (err: any, result: KkSakliListeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pos_Odeme(posOdeme: PosOdeme, callback: (err: any, result: PosOdemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama(tpIslemSorgulama: TpIslemSorgulama, callback: (err: any, result: TpIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama4(tpIslemSorgulama4: TpIslemSorgulama4, callback: (err: any, result: TpIslemSorgulama4Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama5(tpIslemSorgulama5: TpIslemSorgulama5, callback: (err: any, result: TpIslemSorgulama5Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama6(tpIslemSorgulama6: TpIslemSorgulama6, callback: (err: any, result: TpIslemSorgulama6Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama_WP(tpIslemSorgulamaWp: TpIslemSorgulamaWp, callback: (err: any, result: TpIslemSorgulamaWpResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Detay(tpMutabakatDetay: TpMutabakatDetay, callback: (err: any, result: TpMutabakatDetayResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Detay2(tpMutabakatDetay2: TpMutabakatDetay2, callback: (err: any, result: TpMutabakatDetay2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Ozet(tpMutabakatOzet: TpMutabakatOzet, callback: (err: any, result: TpMutabakatOzetResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade(tpIslemIptalIade: TpIslemIptalIade, callback: (err: any, result: TpIslemIptalIadeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade2(tpIslemIptalIade2: TpIslemIptalIade2, callback: (err: any, result: TpIslemIptalIade2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Izleme(tpIslemIzleme: TpIslemIzleme, callback: (err: any, result: TpIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi(tpIslemIptalIadeKismi: TpIslemIptalIadeKismi, callback: (err: any, result: TpIslemIptalIadeKismiResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi2(tpIslemIptalIadeKismi2: TpIslemIptalIadeKismi2, callback: (err: any, result: TpIslemIptalIadeKismi2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi3(tpIslemIptalIadeKismi3: TpIslemIptalIadeKismi3, callback: (err: any, result: TpIslemIptalIadeKismi3Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi4(tpIslemIptalIadeKismi4: TpIslemIptalIadeKismi4, callback: (err: any, result: TpIslemIptalIadeKismi4Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi_WP(tpIslemIptalIadeKismiWp: TpIslemIptalIadeKismiWp, callback: (err: any, result: TpIslemIptalIadeKismiWpResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_OnProv(tpIslemIptalOnProv: TpIslemIptalOnProv, callback: (err: any, result: TpIslemIptalOnProvResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_KK_Verify(tpKkVerify: TpKkVerify, callback: (err: any, result: TpKkVerifyResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_Kapa(tpIslemOdemeOnProvKapa: TpIslemOdemeOnProvKapa, callback: (err: any, result: TpIslemOdemeOnProvKapaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv(tpIslemOdemeOnProv: TpIslemOdemeOnProv, callback: (err: any, result: TpIslemOdemeOnProvResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_WMD(tpIslemOdemeOnProvWmd: TpIslemOdemeOnProvWmd, callback: (err: any, result: TpIslemOdemeOnProvWmdResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_WKS(tpIslemOdemeOnProvWks: TpIslemOdemeOnProvWks, callback: (err: any, result: TpIslemOdemeOnProvWksResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout_SK(tpIslemCheckoutSk: TpIslemCheckoutSk, callback: (err: any, result: TpIslemCheckoutSkResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout(tpIslemCheckout: TpIslemCheckout, callback: (err: any, result: TpIslemCheckoutResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout_Odeme_WNS(tpIslemCheckoutOdemeWns: TpIslemCheckoutOdemeWns, callback: (err: any, result: TpIslemCheckoutOdemeWnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SHA2B64(sha2B64: Sha2B64, callback: (err: any, result: Sha2B64Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Vadeli_Islem_Izleme(vadeliIslemIzleme: VadeliIslemIzleme, callback: (err: any, result: VadeliIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme(pazaryeriTpAltUyeIsyeriEkleme: PazaryeriTpAltUyeIsyeriEkleme, callback: (err: any, result: PazaryeriTpAltUyeIsyeriEklemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme_v2(pazaryeriTpAltUyeIsyeriEklemeV2: PazaryeriTpAltUyeIsyeriEklemeV2, callback: (err: any, result: PazaryeriTpAltUyeIsyeriEklemeV2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme(pazaryeriTpAltUyeIsyeriGuncelleme: PazaryeriTpAltUyeIsyeriGuncelleme, callback: (err: any, result: PazaryeriTpAltUyeIsyeriGuncellemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme_v2(pazaryeriTpAltUyeIsyeriGuncellemeV2: PazaryeriTpAltUyeIsyeriGuncellemeV2, callback: (err: any, result: PazaryeriTpAltUyeIsyeriGuncellemeV2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Liste(pazaryeriTpAltUyeIsyeriListe: PazaryeriTpAltUyeIsyeriListe, callback: (err: any, result: PazaryeriTpAltUyeIsyeriListeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Silme(pazaryeriTpAltUyeIsyeriSilme: PazaryeriTpAltUyeIsyeriSilme, callback: (err: any, result: PazaryeriTpAltUyeIsyeriSilmeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Iptal_Iade(pazaryeriTpIptalIade: PazaryeriTpIptalIade, callback: (err: any, result: PazaryeriTpIptalIadeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Limit_Kontrol(pazaryeriTpLimitKontrol: PazaryeriTpLimitKontrol, callback: (err: any, result: PazaryeriTpLimitKontrolResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Siparis_Detay_Ekle(pazaryeriTpSiparisDetayEkle: PazaryeriTpSiparisDetayEkle, callback: (err: any, result: PazaryeriTpSiparisDetayEkleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailAdd(mpOrderDetailAdd: MpOrderDetailAdd, callback: (err: any, result: MpOrderDetailAddResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailUpdate(mpOrderDetailUpdate: MpOrderDetailUpdate, callback: (err: any, result: MpOrderDetailUpdateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailStatus(mpOrderDetailStatus: MpOrderDetailStatus, callback: (err: any, result: MpOrderDetailStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailQuery(mpOrderDetailQuery: MpOrderDetailQuery, callback: (err: any, result: MpOrderDetailQueryResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderRefund(mpOrderRefund: MpOrderRefund, callback: (err: any, result: MpOrderRefundResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailList(mpOrderDetailList: MpOrderDetailList, callback: (err: any, result: MpOrderDetailListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Modal_Payment(tpModalPayment: TpModalPayment, callback: (err: any, result: TpModalPaymentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Param_Pazaryeri_Islem_Izleme(paramPazaryeriIslemIzleme: ParamPazaryeriIslemIzleme, callback: (err: any, result: ParamPazaryeriIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Siparis_Onay(pazaryeriTpSiparisOnay: PazaryeriTpSiparisOnay, callback: (err: any, result: PazaryeriTpSiparisOnayResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Islem_Sorgulama(pazaryeriTpIslemSorgulama: PazaryeriTpIslemSorgulama, callback: (err: any, result: PazaryeriTpIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pos_Plugin_Bildirim(posPluginBildirim: PosPluginBildirim, callback: (err: any, result: PosPluginBildirimResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Il_Liste(ılListe: IlListe, callback: (err: any, result: IlListeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MoneyPay_Islem_Sorgulama(moneyPayIslemSorgulama: MoneyPayIslemSorgulama, callback: (err: any, result: MoneyPayIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
