import { BinSanalPos1 } from "../definitions/BinSanalPos1";
import { BinSanalPosResponse1 } from "../definitions/BinSanalPosResponse1";
import { BinSanalPos21 } from "../definitions/BinSanalPos21";
import { BinSanalPos2Response1 } from "../definitions/BinSanalPos2Response1";
import { TpOzelOranListe1 } from "../definitions/TpOzelOranListe1";
import { TpOzelOranListeResponse1 } from "../definitions/TpOzelOranListeResponse1";
import { TpOzelOranSkListe1 } from "../definitions/TpOzelOranSkListe1";
import { TpOzelOranSkListeResponse1 } from "../definitions/TpOzelOranSkListeResponse1";
import { TpOzelOranSkGuncelle1 } from "../definitions/TpOzelOranSkGuncelle1";
import { TpOzelOranSkGuncelleResponse1 } from "../definitions/TpOzelOranSkGuncelleResponse1";
import { TpIslemDekontGonder1 } from "../definitions/TpIslemDekontGonder1";
import { TpIslemDekontGonderResponse1 } from "../definitions/TpIslemDekontGonderResponse1";
import { TpIslemOdeme1 } from "../definitions/TpIslemOdeme1";
import { TpIslemOdemeResponse1 } from "../definitions/TpIslemOdemeResponse1";
import { TpWmdPay1 } from "../definitions/TpWmdPay1";
import { TpWmdPayResponse1 } from "../definitions/TpWmdPayResponse1";
import { TpWmdUcdV21 } from "../definitions/TpWmdUcdV21";
import { TpWmdUcdV2Response1 } from "../definitions/TpWmdUcdV2Response1";
import { TpWmdUcd1 } from "../definitions/TpWmdUcd1";
import { TpWmdUcdResponse1 } from "../definitions/TpWmdUcdResponse1";
import { TpWmdUcdWp1 } from "../definitions/TpWmdUcdWp1";
import { TpWmdUcdWpResponse1 } from "../definitions/TpWmdUcdWpResponse1";
import { TpWmdUcdPuan1 } from "../definitions/TpWmdUcdPuan1";
import { TpWmdUcdPuanResponse1 } from "../definitions/TpWmdUcdPuanResponse1";
import { PaymentHopi1 } from "../definitions/PaymentHopi1";
import { PaymentHopiResponse1 } from "../definitions/PaymentHopiResponse1";
import { TpMultiplePayment1 } from "../definitions/TpMultiplePayment1";
import { TpMultiplePaymentResponse1 } from "../definitions/TpMultiplePaymentResponse1";
import { TpMultiplePaymentStatus1 } from "../definitions/TpMultiplePaymentStatus1";
import { TpMultiplePaymentStatusResponse1 } from "../definitions/TpMultiplePaymentStatusResponse1";
import { TpIslemOdemeWns1 } from "../definitions/TpIslemOdemeWns1";
import { TpIslemOdemeWnsResponse1 } from "../definitions/TpIslemOdemeWnsResponse1";
import { TpIslemOdemeWd1 } from "../definitions/TpIslemOdemeWd1";
import { TpIslemOdemeWdResponse1 } from "../definitions/TpIslemOdemeWdResponse1";
import { TpIslemOdemeBkm1 } from "../definitions/TpIslemOdemeBkm1";
import { TpIslemOdemeBkmResponse1 } from "../definitions/TpIslemOdemeBkmResponse1";
import { TpIslemOdemeWks1 } from "../definitions/TpIslemOdemeWks1";
import { TpIslemOdemeWksResponse1 } from "../definitions/TpIslemOdemeWksResponse1";
import { KkSaklama1 } from "../definitions/KkSaklama1";
import { KkSaklamaResponse1 } from "../definitions/KkSaklamaResponse1";
import { KkSakliListe1 } from "../definitions/KkSakliListe1";
import { KkSakliListeResponse1 } from "../definitions/KkSakliListeResponse1";
import { PosOdeme1 } from "../definitions/PosOdeme1";
import { PosOdemeResponse1 } from "../definitions/PosOdemeResponse1";
import { TpIslemSorgulama1 } from "../definitions/TpIslemSorgulama1";
import { TpIslemSorgulamaResponse1 } from "../definitions/TpIslemSorgulamaResponse1";
import { TpIslemSorgulama41 } from "../definitions/TpIslemSorgulama41";
import { TpIslemSorgulama4Response1 } from "../definitions/TpIslemSorgulama4Response1";
import { TpIslemSorgulama51 } from "../definitions/TpIslemSorgulama51";
import { TpIslemSorgulama5Response1 } from "../definitions/TpIslemSorgulama5Response1";
import { TpIslemSorgulama61 } from "../definitions/TpIslemSorgulama61";
import { TpIslemSorgulama6Response1 } from "../definitions/TpIslemSorgulama6Response1";
import { TpIslemSorgulamaWp1 } from "../definitions/TpIslemSorgulamaWp1";
import { TpIslemSorgulamaWpResponse1 } from "../definitions/TpIslemSorgulamaWpResponse1";
import { TpMutabakatDetay1 } from "../definitions/TpMutabakatDetay1";
import { TpMutabakatDetayResponse1 } from "../definitions/TpMutabakatDetayResponse1";
import { TpMutabakatDetay21 } from "../definitions/TpMutabakatDetay21";
import { TpMutabakatDetay2Response1 } from "../definitions/TpMutabakatDetay2Response1";
import { TpMutabakatOzet1 } from "../definitions/TpMutabakatOzet1";
import { TpMutabakatOzetResponse1 } from "../definitions/TpMutabakatOzetResponse1";
import { TpIslemIptalIade1 } from "../definitions/TpIslemIptalIade1";
import { TpIslemIptalIadeResponse1 } from "../definitions/TpIslemIptalIadeResponse1";
import { TpIslemIptalIade21 } from "../definitions/TpIslemIptalIade21";
import { TpIslemIptalIade2Response1 } from "../definitions/TpIslemIptalIade2Response1";
import { TpIslemIzleme1 } from "../definitions/TpIslemIzleme1";
import { TpIslemIzlemeResponse1 } from "../definitions/TpIslemIzlemeResponse1";
import { TpIslemIptalIadeKismi1 } from "../definitions/TpIslemIptalIadeKismi1";
import { TpIslemIptalIadeKismiResponse1 } from "../definitions/TpIslemIptalIadeKismiResponse1";
import { TpIslemIptalIadeKismi21 } from "../definitions/TpIslemIptalIadeKismi21";
import { TpIslemIptalIadeKismi2Response1 } from "../definitions/TpIslemIptalIadeKismi2Response1";
import { TpIslemIptalIadeKismi31 } from "../definitions/TpIslemIptalIadeKismi31";
import { TpIslemIptalIadeKismi3Response1 } from "../definitions/TpIslemIptalIadeKismi3Response1";
import { TpIslemIptalIadeKismi41 } from "../definitions/TpIslemIptalIadeKismi41";
import { TpIslemIptalIadeKismi4Response1 } from "../definitions/TpIslemIptalIadeKismi4Response1";
import { TpIslemIptalIadeKismiWp1 } from "../definitions/TpIslemIptalIadeKismiWp1";
import { TpIslemIptalIadeKismiWpResponse1 } from "../definitions/TpIslemIptalIadeKismiWpResponse1";
import { TpIslemIptalOnProv1 } from "../definitions/TpIslemIptalOnProv1";
import { TpIslemIptalOnProvResponse1 } from "../definitions/TpIslemIptalOnProvResponse1";
import { TpKkVerify1 } from "../definitions/TpKkVerify1";
import { TpKkVerifyResponse1 } from "../definitions/TpKkVerifyResponse1";
import { TpIslemOdemeOnProvKapa1 } from "../definitions/TpIslemOdemeOnProvKapa1";
import { TpIslemOdemeOnProvKapaResponse1 } from "../definitions/TpIslemOdemeOnProvKapaResponse1";
import { TpIslemOdemeOnProv1 } from "../definitions/TpIslemOdemeOnProv1";
import { TpIslemOdemeOnProvResponse1 } from "../definitions/TpIslemOdemeOnProvResponse1";
import { TpIslemOdemeOnProvWmd1 } from "../definitions/TpIslemOdemeOnProvWmd1";
import { TpIslemOdemeOnProvWmdResponse1 } from "../definitions/TpIslemOdemeOnProvWmdResponse1";
import { TpIslemOdemeOnProvWks1 } from "../definitions/TpIslemOdemeOnProvWks1";
import { TpIslemOdemeOnProvWksResponse1 } from "../definitions/TpIslemOdemeOnProvWksResponse1";
import { TpIslemCheckoutSk1 } from "../definitions/TpIslemCheckoutSk1";
import { TpIslemCheckoutSkResponse1 } from "../definitions/TpIslemCheckoutSkResponse1";
import { TpIslemCheckout1 } from "../definitions/TpIslemCheckout1";
import { TpIslemCheckoutResponse1 } from "../definitions/TpIslemCheckoutResponse1";
import { TpIslemCheckoutOdemeWns1 } from "../definitions/TpIslemCheckoutOdemeWns1";
import { TpIslemCheckoutOdemeWnsResponse1 } from "../definitions/TpIslemCheckoutOdemeWnsResponse1";
import { Sha2B641 } from "../definitions/Sha2B641";
import { Sha2B64Response1 } from "../definitions/Sha2B64Response1";
import { VadeliIslemIzleme1 } from "../definitions/VadeliIslemIzleme1";
import { VadeliIslemIzlemeResponse1 } from "../definitions/VadeliIslemIzlemeResponse1";
import { PazaryeriTpAltUyeIsyeriEkleme1 } from "../definitions/PazaryeriTpAltUyeIsyeriEkleme1";
import { PazaryeriTpAltUyeIsyeriEklemeResponse1 } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeResponse1";
import { PazaryeriTpAltUyeIsyeriEklemeV21 } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeV21";
import { PazaryeriTpAltUyeIsyeriEklemeV2Response1 } from "../definitions/PazaryeriTpAltUyeIsyeriEklemeV2Response1";
import { PazaryeriTpAltUyeIsyeriGuncelleme1 } from "../definitions/PazaryeriTpAltUyeIsyeriGuncelleme1";
import { PazaryeriTpAltUyeIsyeriGuncellemeResponse1 } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeResponse1";
import { PazaryeriTpAltUyeIsyeriGuncellemeV21 } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeV21";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2Response1 } from "../definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2Response1";
import { PazaryeriTpAltUyeIsyeriListe1 } from "../definitions/PazaryeriTpAltUyeIsyeriListe1";
import { PazaryeriTpAltUyeIsyeriListeResponse1 } from "../definitions/PazaryeriTpAltUyeIsyeriListeResponse1";
import { PazaryeriTpAltUyeIsyeriSilme1 } from "../definitions/PazaryeriTpAltUyeIsyeriSilme1";
import { PazaryeriTpAltUyeIsyeriSilmeResponse1 } from "../definitions/PazaryeriTpAltUyeIsyeriSilmeResponse1";
import { PazaryeriTpIptalIade1 } from "../definitions/PazaryeriTpIptalIade1";
import { PazaryeriTpIptalIadeResponse1 } from "../definitions/PazaryeriTpIptalIadeResponse1";
import { PazaryeriTpLimitKontrol1 } from "../definitions/PazaryeriTpLimitKontrol1";
import { PazaryeriTpLimitKontrolResponse1 } from "../definitions/PazaryeriTpLimitKontrolResponse1";
import { PazaryeriTpSiparisDetayEkle1 } from "../definitions/PazaryeriTpSiparisDetayEkle1";
import { PazaryeriTpSiparisDetayEkleResponse1 } from "../definitions/PazaryeriTpSiparisDetayEkleResponse1";
import { MpOrderDetailAdd1 } from "../definitions/MpOrderDetailAdd1";
import { MpOrderDetailAddResponse1 } from "../definitions/MpOrderDetailAddResponse1";
import { MpOrderDetailUpdate1 } from "../definitions/MpOrderDetailUpdate1";
import { MpOrderDetailUpdateResponse1 } from "../definitions/MpOrderDetailUpdateResponse1";
import { MpOrderDetailStatus1 } from "../definitions/MpOrderDetailStatus1";
import { MpOrderDetailStatusResponse1 } from "../definitions/MpOrderDetailStatusResponse1";
import { MpOrderDetailQuery1 } from "../definitions/MpOrderDetailQuery1";
import { MpOrderDetailQueryResponse1 } from "../definitions/MpOrderDetailQueryResponse1";
import { MpOrderRefund1 } from "../definitions/MpOrderRefund1";
import { MpOrderRefundResponse1 } from "../definitions/MpOrderRefundResponse1";
import { MpOrderDetailList1 } from "../definitions/MpOrderDetailList1";
import { MpOrderDetailListResponse1 } from "../definitions/MpOrderDetailListResponse1";
import { TpModalPayment1 } from "../definitions/TpModalPayment1";
import { TpModalPaymentResponse1 } from "../definitions/TpModalPaymentResponse1";
import { ParamPazaryeriIslemIzleme1 } from "../definitions/ParamPazaryeriIslemIzleme1";
import { ParamPazaryeriIslemIzlemeResponse1 } from "../definitions/ParamPazaryeriIslemIzlemeResponse1";
import { PazaryeriTpSiparisOnay1 } from "../definitions/PazaryeriTpSiparisOnay1";
import { PazaryeriTpSiparisOnayResponse1 } from "../definitions/PazaryeriTpSiparisOnayResponse1";
import { PazaryeriTpIslemSorgulama1 } from "../definitions/PazaryeriTpIslemSorgulama1";
import { PazaryeriTpIslemSorgulamaResponse1 } from "../definitions/PazaryeriTpIslemSorgulamaResponse1";
import { PosPluginBildirim1 } from "../definitions/PosPluginBildirim1";
import { PosPluginBildirimResponse1 } from "../definitions/PosPluginBildirimResponse1";
import { IlListe1 } from "../definitions/IlListe1";
import { IlListeResponse1 } from "../definitions/IlListeResponse1";
import { MoneyPayIslemSorgulama1 } from "../definitions/MoneyPayIslemSorgulama1";
import { MoneyPayIslemSorgulamaResponse1 } from "../definitions/MoneyPayIslemSorgulamaResponse1";

export interface TurkPosX0020WsX0020TestSoap12 {
    BIN_SanalPos(bınSanalPos: BinSanalPos1, callback: (err: any, result: BinSanalPosResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    BIN_SanalPos2(bınSanalPos2: BinSanalPos21, callback: (err: any, result: BinSanalPos2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_Liste(tpOzelOranListe: TpOzelOranListe1, callback: (err: any, result: TpOzelOranListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_SK_Liste(tpOzelOranSkListe: TpOzelOranSkListe1, callback: (err: any, result: TpOzelOranSkListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Ozel_Oran_SK_Guncelle(tpOzelOranSkGuncelle: TpOzelOranSkGuncelle1, callback: (err: any, result: TpOzelOranSkGuncelleResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Dekont_Gonder(tpIslemDekontGonder: TpIslemDekontGonder1, callback: (err: any, result: TpIslemDekontGonderResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme(tpIslemOdeme: TpIslemOdeme1, callback: (err: any, result: TpIslemOdemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_Pay(tpWmdPay: TpWmdPay1, callback: (err: any, result: TpWmdPayResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_v2(tpWmdUcdV2: TpWmdUcdV21, callback: (err: any, result: TpWmdUcdV2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD(tpWmdUcd: TpWmdUcd1, callback: (err: any, result: TpWmdUcdResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_WP(tpWmdUcdWp: TpWmdUcdWp1, callback: (err: any, result: TpWmdUcdWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_WMD_UCD_Puan(tpWmdUcdPuan: TpWmdUcdPuan1, callback: (err: any, result: TpWmdUcdPuanResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Payment_Hopi(paymentHopi: PaymentHopi1, callback: (err: any, result: PaymentHopiResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Multiple_Payment(tpMultiplePayment: TpMultiplePayment1, callback: (err: any, result: TpMultiplePaymentResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Multiple_Payment_Status(tpMultiplePaymentStatus: TpMultiplePaymentStatus1, callback: (err: any, result: TpMultiplePaymentStatusResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WNS(tpIslemOdemeWns: TpIslemOdemeWns1, callback: (err: any, result: TpIslemOdemeWnsResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WD(tpIslemOdemeWd: TpIslemOdemeWd1, callback: (err: any, result: TpIslemOdemeWdResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_BKM(tpIslemOdemeBkm: TpIslemOdemeBkm1, callback: (err: any, result: TpIslemOdemeBkmResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_WKS(tpIslemOdemeWks: TpIslemOdemeWks1, callback: (err: any, result: TpIslemOdemeWksResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    KK_Saklama(kkSaklama: KkSaklama1, callback: (err: any, result: KkSaklamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    KK_Sakli_Liste(kkSakliListe: KkSakliListe1, callback: (err: any, result: KkSakliListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pos_Odeme(posOdeme: PosOdeme1, callback: (err: any, result: PosOdemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama(tpIslemSorgulama: TpIslemSorgulama1, callback: (err: any, result: TpIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama4(tpIslemSorgulama4: TpIslemSorgulama41, callback: (err: any, result: TpIslemSorgulama4Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama5(tpIslemSorgulama5: TpIslemSorgulama51, callback: (err: any, result: TpIslemSorgulama5Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama6(tpIslemSorgulama6: TpIslemSorgulama61, callback: (err: any, result: TpIslemSorgulama6Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Sorgulama_WP(tpIslemSorgulamaWp: TpIslemSorgulamaWp1, callback: (err: any, result: TpIslemSorgulamaWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Detay(tpMutabakatDetay: TpMutabakatDetay1, callback: (err: any, result: TpMutabakatDetayResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Detay2(tpMutabakatDetay2: TpMutabakatDetay21, callback: (err: any, result: TpMutabakatDetay2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Mutabakat_Ozet(tpMutabakatOzet: TpMutabakatOzet1, callback: (err: any, result: TpMutabakatOzetResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade(tpIslemIptalIade: TpIslemIptalIade1, callback: (err: any, result: TpIslemIptalIadeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade2(tpIslemIptalIade2: TpIslemIptalIade21, callback: (err: any, result: TpIslemIptalIade2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Izleme(tpIslemIzleme: TpIslemIzleme1, callback: (err: any, result: TpIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi(tpIslemIptalIadeKismi: TpIslemIptalIadeKismi1, callback: (err: any, result: TpIslemIptalIadeKismiResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi2(tpIslemIptalIadeKismi2: TpIslemIptalIadeKismi21, callback: (err: any, result: TpIslemIptalIadeKismi2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi3(tpIslemIptalIadeKismi3: TpIslemIptalIadeKismi31, callback: (err: any, result: TpIslemIptalIadeKismi3Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi4(tpIslemIptalIadeKismi4: TpIslemIptalIadeKismi41, callback: (err: any, result: TpIslemIptalIadeKismi4Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_Iade_Kismi_WP(tpIslemIptalIadeKismiWp: TpIslemIptalIadeKismiWp1, callback: (err: any, result: TpIslemIptalIadeKismiWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Iptal_OnProv(tpIslemIptalOnProv: TpIslemIptalOnProv1, callback: (err: any, result: TpIslemIptalOnProvResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_KK_Verify(tpKkVerify: TpKkVerify1, callback: (err: any, result: TpKkVerifyResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_Kapa(tpIslemOdemeOnProvKapa: TpIslemOdemeOnProvKapa1, callback: (err: any, result: TpIslemOdemeOnProvKapaResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv(tpIslemOdemeOnProv: TpIslemOdemeOnProv1, callback: (err: any, result: TpIslemOdemeOnProvResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_WMD(tpIslemOdemeOnProvWmd: TpIslemOdemeOnProvWmd1, callback: (err: any, result: TpIslemOdemeOnProvWmdResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Odeme_OnProv_WKS(tpIslemOdemeOnProvWks: TpIslemOdemeOnProvWks1, callback: (err: any, result: TpIslemOdemeOnProvWksResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout_SK(tpIslemCheckoutSk: TpIslemCheckoutSk1, callback: (err: any, result: TpIslemCheckoutSkResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout(tpIslemCheckout: TpIslemCheckout1, callback: (err: any, result: TpIslemCheckoutResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Islem_Checkout_Odeme_WNS(tpIslemCheckoutOdemeWns: TpIslemCheckoutOdemeWns1, callback: (err: any, result: TpIslemCheckoutOdemeWnsResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SHA2B64(sha2B64: Sha2B641, callback: (err: any, result: Sha2B64Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Vadeli_Islem_Izleme(vadeliIslemIzleme: VadeliIslemIzleme1, callback: (err: any, result: VadeliIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme(pazaryeriTpAltUyeIsyeriEkleme: PazaryeriTpAltUyeIsyeriEkleme1, callback: (err: any, result: PazaryeriTpAltUyeIsyeriEklemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme_v2(pazaryeriTpAltUyeIsyeriEklemeV2: PazaryeriTpAltUyeIsyeriEklemeV21, callback: (err: any, result: PazaryeriTpAltUyeIsyeriEklemeV2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme(pazaryeriTpAltUyeIsyeriGuncelleme: PazaryeriTpAltUyeIsyeriGuncelleme1, callback: (err: any, result: PazaryeriTpAltUyeIsyeriGuncellemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme_v2(pazaryeriTpAltUyeIsyeriGuncellemeV2: PazaryeriTpAltUyeIsyeriGuncellemeV21, callback: (err: any, result: PazaryeriTpAltUyeIsyeriGuncellemeV2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Liste(pazaryeriTpAltUyeIsyeriListe: PazaryeriTpAltUyeIsyeriListe1, callback: (err: any, result: PazaryeriTpAltUyeIsyeriListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_AltUyeIsyeri_Silme(pazaryeriTpAltUyeIsyeriSilme: PazaryeriTpAltUyeIsyeriSilme1, callback: (err: any, result: PazaryeriTpAltUyeIsyeriSilmeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Iptal_Iade(pazaryeriTpIptalIade: PazaryeriTpIptalIade1, callback: (err: any, result: PazaryeriTpIptalIadeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Limit_Kontrol(pazaryeriTpLimitKontrol: PazaryeriTpLimitKontrol1, callback: (err: any, result: PazaryeriTpLimitKontrolResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Siparis_Detay_Ekle(pazaryeriTpSiparisDetayEkle: PazaryeriTpSiparisDetayEkle1, callback: (err: any, result: PazaryeriTpSiparisDetayEkleResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailAdd(mpOrderDetailAdd: MpOrderDetailAdd1, callback: (err: any, result: MpOrderDetailAddResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailUpdate(mpOrderDetailUpdate: MpOrderDetailUpdate1, callback: (err: any, result: MpOrderDetailUpdateResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailStatus(mpOrderDetailStatus: MpOrderDetailStatus1, callback: (err: any, result: MpOrderDetailStatusResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailQuery(mpOrderDetailQuery: MpOrderDetailQuery1, callback: (err: any, result: MpOrderDetailQueryResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderRefund(mpOrderRefund: MpOrderRefund1, callback: (err: any, result: MpOrderRefundResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MP_OrderDetailList(mpOrderDetailList: MpOrderDetailList1, callback: (err: any, result: MpOrderDetailListResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TP_Modal_Payment(tpModalPayment: TpModalPayment1, callback: (err: any, result: TpModalPaymentResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Param_Pazaryeri_Islem_Izleme(paramPazaryeriIslemIzleme: ParamPazaryeriIslemIzleme1, callback: (err: any, result: ParamPazaryeriIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Siparis_Onay(pazaryeriTpSiparisOnay: PazaryeriTpSiparisOnay1, callback: (err: any, result: PazaryeriTpSiparisOnayResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pazaryeri_TP_Islem_Sorgulama(pazaryeriTpIslemSorgulama: PazaryeriTpIslemSorgulama1, callback: (err: any, result: PazaryeriTpIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Pos_Plugin_Bildirim(posPluginBildirim: PosPluginBildirim1, callback: (err: any, result: PosPluginBildirimResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    Il_Liste(ılListe: IlListe1, callback: (err: any, result: IlListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MoneyPay_Islem_Sorgulama(moneyPayIslemSorgulama: MoneyPayIslemSorgulama1, callback: (err: any, result: MoneyPayIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
