import { Client as SoapClient, createClientAsync as soapCreateClientAsync } from "soap";
import { BinSanalPos } from "./definitions/BinSanalPos";
import { BinSanalPosResponse } from "./definitions/BinSanalPosResponse";
import { BinSanalPos2 } from "./definitions/BinSanalPos2";
import { BinSanalPos2Response } from "./definitions/BinSanalPos2Response";
import { TpOzelOranListe } from "./definitions/TpOzelOranListe";
import { TpOzelOranListeResponse } from "./definitions/TpOzelOranListeResponse";
import { TpOzelOranSkListe } from "./definitions/TpOzelOranSkListe";
import { TpOzelOranSkListeResponse } from "./definitions/TpOzelOranSkListeResponse";
import { TpOzelOranSkGuncelle } from "./definitions/TpOzelOranSkGuncelle";
import { TpOzelOranSkGuncelleResponse } from "./definitions/TpOzelOranSkGuncelleResponse";
import { TpIslemDekontGonder } from "./definitions/TpIslemDekontGonder";
import { TpIslemDekontGonderResponse } from "./definitions/TpIslemDekontGonderResponse";
import { TpIslemOdeme } from "./definitions/TpIslemOdeme";
import { TpIslemOdemeResponse } from "./definitions/TpIslemOdemeResponse";
import { TpWmdPay } from "./definitions/TpWmdPay";
import { TpWmdPayResponse } from "./definitions/TpWmdPayResponse";
import { TpWmdUcdV2 } from "./definitions/TpWmdUcdV2";
import { TpWmdUcdV2Response } from "./definitions/TpWmdUcdV2Response";
import { TpWmdUcd } from "./definitions/TpWmdUcd";
import { TpWmdUcdResponse } from "./definitions/TpWmdUcdResponse";
import { TpWmdUcdWp } from "./definitions/TpWmdUcdWp";
import { TpWmdUcdWpResponse } from "./definitions/TpWmdUcdWpResponse";
import { TpWmdUcdPuan } from "./definitions/TpWmdUcdPuan";
import { TpWmdUcdPuanResponse } from "./definitions/TpWmdUcdPuanResponse";
import { PaymentHopi } from "./definitions/PaymentHopi";
import { PaymentHopiResponse } from "./definitions/PaymentHopiResponse";
import { TpMultiplePayment } from "./definitions/TpMultiplePayment";
import { TpMultiplePaymentResponse } from "./definitions/TpMultiplePaymentResponse";
import { TpMultiplePaymentStatus } from "./definitions/TpMultiplePaymentStatus";
import { TpMultiplePaymentStatusResponse } from "./definitions/TpMultiplePaymentStatusResponse";
import { TpIslemOdemeWns } from "./definitions/TpIslemOdemeWns";
import { TpIslemOdemeWnsResponse } from "./definitions/TpIslemOdemeWnsResponse";
import { TpIslemOdemeWd } from "./definitions/TpIslemOdemeWd";
import { TpIslemOdemeWdResponse } from "./definitions/TpIslemOdemeWdResponse";
import { TpIslemOdemeBkm } from "./definitions/TpIslemOdemeBkm";
import { TpIslemOdemeBkmResponse } from "./definitions/TpIslemOdemeBkmResponse";
import { TpIslemOdemeWks } from "./definitions/TpIslemOdemeWks";
import { TpIslemOdemeWksResponse } from "./definitions/TpIslemOdemeWksResponse";
import { KkSaklama } from "./definitions/KkSaklama";
import { KkSaklamaResponse } from "./definitions/KkSaklamaResponse";
import { KkSakliListe } from "./definitions/KkSakliListe";
import { KkSakliListeResponse } from "./definitions/KkSakliListeResponse";
import { PosOdeme } from "./definitions/PosOdeme";
import { PosOdemeResponse } from "./definitions/PosOdemeResponse";
import { TpIslemSorgulama } from "./definitions/TpIslemSorgulama";
import { TpIslemSorgulamaResponse } from "./definitions/TpIslemSorgulamaResponse";
import { TpIslemSorgulama4 } from "./definitions/TpIslemSorgulama4";
import { TpIslemSorgulama4Response } from "./definitions/TpIslemSorgulama4Response";
import { TpIslemSorgulama5 } from "./definitions/TpIslemSorgulama5";
import { TpIslemSorgulama5Response } from "./definitions/TpIslemSorgulama5Response";
import { TpIslemSorgulama6 } from "./definitions/TpIslemSorgulama6";
import { TpIslemSorgulama6Response } from "./definitions/TpIslemSorgulama6Response";
import { TpIslemSorgulamaWp } from "./definitions/TpIslemSorgulamaWp";
import { TpIslemSorgulamaWpResponse } from "./definitions/TpIslemSorgulamaWpResponse";
import { TpMutabakatDetay } from "./definitions/TpMutabakatDetay";
import { TpMutabakatDetayResponse } from "./definitions/TpMutabakatDetayResponse";
import { TpMutabakatDetay2 } from "./definitions/TpMutabakatDetay2";
import { TpMutabakatDetay2Response } from "./definitions/TpMutabakatDetay2Response";
import { TpMutabakatOzet } from "./definitions/TpMutabakatOzet";
import { TpMutabakatOzetResponse } from "./definitions/TpMutabakatOzetResponse";
import { TpIslemIptalIade } from "./definitions/TpIslemIptalIade";
import { TpIslemIptalIadeResponse } from "./definitions/TpIslemIptalIadeResponse";
import { TpIslemIptalIade2 } from "./definitions/TpIslemIptalIade2";
import { TpIslemIptalIade2Response } from "./definitions/TpIslemIptalIade2Response";
import { TpIslemIzleme } from "./definitions/TpIslemIzleme";
import { TpIslemIzlemeResponse } from "./definitions/TpIslemIzlemeResponse";
import { TpIslemIptalIadeKismi } from "./definitions/TpIslemIptalIadeKismi";
import { TpIslemIptalIadeKismiResponse } from "./definitions/TpIslemIptalIadeKismiResponse";
import { TpIslemIptalIadeKismi2 } from "./definitions/TpIslemIptalIadeKismi2";
import { TpIslemIptalIadeKismi2Response } from "./definitions/TpIslemIptalIadeKismi2Response";
import { TpIslemIptalIadeKismi3 } from "./definitions/TpIslemIptalIadeKismi3";
import { TpIslemIptalIadeKismi3Response } from "./definitions/TpIslemIptalIadeKismi3Response";
import { TpIslemIptalIadeKismi4 } from "./definitions/TpIslemIptalIadeKismi4";
import { TpIslemIptalIadeKismi4Response } from "./definitions/TpIslemIptalIadeKismi4Response";
import { TpIslemIptalIadeKismiWp } from "./definitions/TpIslemIptalIadeKismiWp";
import { TpIslemIptalIadeKismiWpResponse } from "./definitions/TpIslemIptalIadeKismiWpResponse";
import { TpIslemIptalOnProv } from "./definitions/TpIslemIptalOnProv";
import { TpIslemIptalOnProvResponse } from "./definitions/TpIslemIptalOnProvResponse";
import { TpKkVerify } from "./definitions/TpKkVerify";
import { TpKkVerifyResponse } from "./definitions/TpKkVerifyResponse";
import { TpIslemOdemeOnProvKapa } from "./definitions/TpIslemOdemeOnProvKapa";
import { TpIslemOdemeOnProvKapaResponse } from "./definitions/TpIslemOdemeOnProvKapaResponse";
import { TpIslemOdemeOnProv } from "./definitions/TpIslemOdemeOnProv";
import { TpIslemOdemeOnProvResponse } from "./definitions/TpIslemOdemeOnProvResponse";
import { TpIslemOdemeOnProvWmd } from "./definitions/TpIslemOdemeOnProvWmd";
import { TpIslemOdemeOnProvWmdResponse } from "./definitions/TpIslemOdemeOnProvWmdResponse";
import { TpIslemOdemeOnProvWks } from "./definitions/TpIslemOdemeOnProvWks";
import { TpIslemOdemeOnProvWksResponse } from "./definitions/TpIslemOdemeOnProvWksResponse";
import { TpIslemCheckoutSk } from "./definitions/TpIslemCheckoutSk";
import { TpIslemCheckoutSkResponse } from "./definitions/TpIslemCheckoutSkResponse";
import { TpIslemCheckout } from "./definitions/TpIslemCheckout";
import { TpIslemCheckoutResponse } from "./definitions/TpIslemCheckoutResponse";
import { TpIslemCheckoutOdemeWns } from "./definitions/TpIslemCheckoutOdemeWns";
import { TpIslemCheckoutOdemeWnsResponse } from "./definitions/TpIslemCheckoutOdemeWnsResponse";
import { Sha2B64 } from "./definitions/Sha2B64";
import { Sha2B64Response } from "./definitions/Sha2B64Response";
import { VadeliIslemIzleme } from "./definitions/VadeliIslemIzleme";
import { VadeliIslemIzlemeResponse } from "./definitions/VadeliIslemIzlemeResponse";
import { PazaryeriTpAltUyeIsyeriEkleme } from "./definitions/PazaryeriTpAltUyeIsyeriEkleme";
import { PazaryeriTpAltUyeIsyeriEklemeResponse } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeResponse";
import { PazaryeriTpAltUyeIsyeriEklemeV2 } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeV2";
import { PazaryeriTpAltUyeIsyeriEklemeV2Response } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeV2Response";
import { PazaryeriTpAltUyeIsyeriGuncelleme } from "./definitions/PazaryeriTpAltUyeIsyeriGuncelleme";
import { PazaryeriTpAltUyeIsyeriGuncellemeResponse } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeResponse";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2 } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2Response } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2Response";
import { PazaryeriTpAltUyeIsyeriListe } from "./definitions/PazaryeriTpAltUyeIsyeriListe";
import { PazaryeriTpAltUyeIsyeriListeResponse } from "./definitions/PazaryeriTpAltUyeIsyeriListeResponse";
import { PazaryeriTpAltUyeIsyeriSilme } from "./definitions/PazaryeriTpAltUyeIsyeriSilme";
import { PazaryeriTpAltUyeIsyeriSilmeResponse } from "./definitions/PazaryeriTpAltUyeIsyeriSilmeResponse";
import { PazaryeriTpIptalIade } from "./definitions/PazaryeriTpIptalIade";
import { PazaryeriTpIptalIadeResponse } from "./definitions/PazaryeriTpIptalIadeResponse";
import { PazaryeriTpLimitKontrol } from "./definitions/PazaryeriTpLimitKontrol";
import { PazaryeriTpLimitKontrolResponse } from "./definitions/PazaryeriTpLimitKontrolResponse";
import { PazaryeriTpSiparisDetayEkle } from "./definitions/PazaryeriTpSiparisDetayEkle";
import { PazaryeriTpSiparisDetayEkleResponse } from "./definitions/PazaryeriTpSiparisDetayEkleResponse";
import { MpOrderDetailAdd } from "./definitions/MpOrderDetailAdd";
import { MpOrderDetailAddResponse } from "./definitions/MpOrderDetailAddResponse";
import { MpOrderDetailUpdate } from "./definitions/MpOrderDetailUpdate";
import { MpOrderDetailUpdateResponse } from "./definitions/MpOrderDetailUpdateResponse";
import { MpOrderDetailStatus } from "./definitions/MpOrderDetailStatus";
import { MpOrderDetailStatusResponse } from "./definitions/MpOrderDetailStatusResponse";
import { MpOrderDetailQuery } from "./definitions/MpOrderDetailQuery";
import { MpOrderDetailQueryResponse } from "./definitions/MpOrderDetailQueryResponse";
import { MpOrderRefund } from "./definitions/MpOrderRefund";
import { MpOrderRefundResponse } from "./definitions/MpOrderRefundResponse";
import { MpOrderDetailList } from "./definitions/MpOrderDetailList";
import { MpOrderDetailListResponse } from "./definitions/MpOrderDetailListResponse";
import { TpModalPayment } from "./definitions/TpModalPayment";
import { TpModalPaymentResponse } from "./definitions/TpModalPaymentResponse";
import { ParamPazaryeriIslemIzleme } from "./definitions/ParamPazaryeriIslemIzleme";
import { ParamPazaryeriIslemIzlemeResponse } from "./definitions/ParamPazaryeriIslemIzlemeResponse";
import { PazaryeriTpSiparisOnay } from "./definitions/PazaryeriTpSiparisOnay";
import { PazaryeriTpSiparisOnayResponse } from "./definitions/PazaryeriTpSiparisOnayResponse";
import { PazaryeriTpIslemSorgulama } from "./definitions/PazaryeriTpIslemSorgulama";
import { PazaryeriTpIslemSorgulamaResponse } from "./definitions/PazaryeriTpIslemSorgulamaResponse";
import { PosPluginBildirim } from "./definitions/PosPluginBildirim";
import { PosPluginBildirimResponse } from "./definitions/PosPluginBildirimResponse";
import { IlListe } from "./definitions/IlListe";
import { IlListeResponse } from "./definitions/IlListeResponse";
import { MoneyPayIslemSorgulama } from "./definitions/MoneyPayIslemSorgulama";
import { MoneyPayIslemSorgulamaResponse } from "./definitions/MoneyPayIslemSorgulamaResponse";
import { BinSanalPos1 } from "./definitions/BinSanalPos1";
import { BinSanalPosResponse1 } from "./definitions/BinSanalPosResponse1";
import { BinSanalPos21 } from "./definitions/BinSanalPos21";
import { BinSanalPos2Response1 } from "./definitions/BinSanalPos2Response1";
import { TpOzelOranListe1 } from "./definitions/TpOzelOranListe1";
import { TpOzelOranListeResponse1 } from "./definitions/TpOzelOranListeResponse1";
import { TpOzelOranSkListe1 } from "./definitions/TpOzelOranSkListe1";
import { TpOzelOranSkListeResponse1 } from "./definitions/TpOzelOranSkListeResponse1";
import { TpOzelOranSkGuncelle1 } from "./definitions/TpOzelOranSkGuncelle1";
import { TpOzelOranSkGuncelleResponse1 } from "./definitions/TpOzelOranSkGuncelleResponse1";
import { TpIslemDekontGonder1 } from "./definitions/TpIslemDekontGonder1";
import { TpIslemDekontGonderResponse1 } from "./definitions/TpIslemDekontGonderResponse1";
import { TpIslemOdeme1 } from "./definitions/TpIslemOdeme1";
import { TpIslemOdemeResponse1 } from "./definitions/TpIslemOdemeResponse1";
import { TpWmdPay1 } from "./definitions/TpWmdPay1";
import { TpWmdPayResponse1 } from "./definitions/TpWmdPayResponse1";
import { TpWmdUcdV21 } from "./definitions/TpWmdUcdV21";
import { TpWmdUcdV2Response1 } from "./definitions/TpWmdUcdV2Response1";
import { TpWmdUcd1 } from "./definitions/TpWmdUcd1";
import { TpWmdUcdResponse1 } from "./definitions/TpWmdUcdResponse1";
import { TpWmdUcdWp1 } from "./definitions/TpWmdUcdWp1";
import { TpWmdUcdWpResponse1 } from "./definitions/TpWmdUcdWpResponse1";
import { TpWmdUcdPuan1 } from "./definitions/TpWmdUcdPuan1";
import { TpWmdUcdPuanResponse1 } from "./definitions/TpWmdUcdPuanResponse1";
import { PaymentHopi1 } from "./definitions/PaymentHopi1";
import { PaymentHopiResponse1 } from "./definitions/PaymentHopiResponse1";
import { TpMultiplePayment1 } from "./definitions/TpMultiplePayment1";
import { TpMultiplePaymentResponse1 } from "./definitions/TpMultiplePaymentResponse1";
import { TpMultiplePaymentStatus1 } from "./definitions/TpMultiplePaymentStatus1";
import { TpMultiplePaymentStatusResponse1 } from "./definitions/TpMultiplePaymentStatusResponse1";
import { TpIslemOdemeWns1 } from "./definitions/TpIslemOdemeWns1";
import { TpIslemOdemeWnsResponse1 } from "./definitions/TpIslemOdemeWnsResponse1";
import { TpIslemOdemeWd1 } from "./definitions/TpIslemOdemeWd1";
import { TpIslemOdemeWdResponse1 } from "./definitions/TpIslemOdemeWdResponse1";
import { TpIslemOdemeBkm1 } from "./definitions/TpIslemOdemeBkm1";
import { TpIslemOdemeBkmResponse1 } from "./definitions/TpIslemOdemeBkmResponse1";
import { TpIslemOdemeWks1 } from "./definitions/TpIslemOdemeWks1";
import { TpIslemOdemeWksResponse1 } from "./definitions/TpIslemOdemeWksResponse1";
import { KkSaklama1 } from "./definitions/KkSaklama1";
import { KkSaklamaResponse1 } from "./definitions/KkSaklamaResponse1";
import { KkSakliListe1 } from "./definitions/KkSakliListe1";
import { KkSakliListeResponse1 } from "./definitions/KkSakliListeResponse1";
import { PosOdeme1 } from "./definitions/PosOdeme1";
import { PosOdemeResponse1 } from "./definitions/PosOdemeResponse1";
import { TpIslemSorgulama1 } from "./definitions/TpIslemSorgulama1";
import { TpIslemSorgulamaResponse1 } from "./definitions/TpIslemSorgulamaResponse1";
import { TpIslemSorgulama41 } from "./definitions/TpIslemSorgulama41";
import { TpIslemSorgulama4Response1 } from "./definitions/TpIslemSorgulama4Response1";
import { TpIslemSorgulama51 } from "./definitions/TpIslemSorgulama51";
import { TpIslemSorgulama5Response1 } from "./definitions/TpIslemSorgulama5Response1";
import { TpIslemSorgulama61 } from "./definitions/TpIslemSorgulama61";
import { TpIslemSorgulama6Response1 } from "./definitions/TpIslemSorgulama6Response1";
import { TpIslemSorgulamaWp1 } from "./definitions/TpIslemSorgulamaWp1";
import { TpIslemSorgulamaWpResponse1 } from "./definitions/TpIslemSorgulamaWpResponse1";
import { TpMutabakatDetay1 } from "./definitions/TpMutabakatDetay1";
import { TpMutabakatDetayResponse1 } from "./definitions/TpMutabakatDetayResponse1";
import { TpMutabakatDetay21 } from "./definitions/TpMutabakatDetay21";
import { TpMutabakatDetay2Response1 } from "./definitions/TpMutabakatDetay2Response1";
import { TpMutabakatOzet1 } from "./definitions/TpMutabakatOzet1";
import { TpMutabakatOzetResponse1 } from "./definitions/TpMutabakatOzetResponse1";
import { TpIslemIptalIade1 } from "./definitions/TpIslemIptalIade1";
import { TpIslemIptalIadeResponse1 } from "./definitions/TpIslemIptalIadeResponse1";
import { TpIslemIptalIade21 } from "./definitions/TpIslemIptalIade21";
import { TpIslemIptalIade2Response1 } from "./definitions/TpIslemIptalIade2Response1";
import { TpIslemIzleme1 } from "./definitions/TpIslemIzleme1";
import { TpIslemIzlemeResponse1 } from "./definitions/TpIslemIzlemeResponse1";
import { TpIslemIptalIadeKismi1 } from "./definitions/TpIslemIptalIadeKismi1";
import { TpIslemIptalIadeKismiResponse1 } from "./definitions/TpIslemIptalIadeKismiResponse1";
import { TpIslemIptalIadeKismi21 } from "./definitions/TpIslemIptalIadeKismi21";
import { TpIslemIptalIadeKismi2Response1 } from "./definitions/TpIslemIptalIadeKismi2Response1";
import { TpIslemIptalIadeKismi31 } from "./definitions/TpIslemIptalIadeKismi31";
import { TpIslemIptalIadeKismi3Response1 } from "./definitions/TpIslemIptalIadeKismi3Response1";
import { TpIslemIptalIadeKismi41 } from "./definitions/TpIslemIptalIadeKismi41";
import { TpIslemIptalIadeKismi4Response1 } from "./definitions/TpIslemIptalIadeKismi4Response1";
import { TpIslemIptalIadeKismiWp1 } from "./definitions/TpIslemIptalIadeKismiWp1";
import { TpIslemIptalIadeKismiWpResponse1 } from "./definitions/TpIslemIptalIadeKismiWpResponse1";
import { TpIslemIptalOnProv1 } from "./definitions/TpIslemIptalOnProv1";
import { TpIslemIptalOnProvResponse1 } from "./definitions/TpIslemIptalOnProvResponse1";
import { TpKkVerify1 } from "./definitions/TpKkVerify1";
import { TpKkVerifyResponse1 } from "./definitions/TpKkVerifyResponse1";
import { TpIslemOdemeOnProvKapa1 } from "./definitions/TpIslemOdemeOnProvKapa1";
import { TpIslemOdemeOnProvKapaResponse1 } from "./definitions/TpIslemOdemeOnProvKapaResponse1";
import { TpIslemOdemeOnProv1 } from "./definitions/TpIslemOdemeOnProv1";
import { TpIslemOdemeOnProvResponse1 } from "./definitions/TpIslemOdemeOnProvResponse1";
import { TpIslemOdemeOnProvWmd1 } from "./definitions/TpIslemOdemeOnProvWmd1";
import { TpIslemOdemeOnProvWmdResponse1 } from "./definitions/TpIslemOdemeOnProvWmdResponse1";
import { TpIslemOdemeOnProvWks1 } from "./definitions/TpIslemOdemeOnProvWks1";
import { TpIslemOdemeOnProvWksResponse1 } from "./definitions/TpIslemOdemeOnProvWksResponse1";
import { TpIslemCheckoutSk1 } from "./definitions/TpIslemCheckoutSk1";
import { TpIslemCheckoutSkResponse1 } from "./definitions/TpIslemCheckoutSkResponse1";
import { TpIslemCheckout1 } from "./definitions/TpIslemCheckout1";
import { TpIslemCheckoutResponse1 } from "./definitions/TpIslemCheckoutResponse1";
import { TpIslemCheckoutOdemeWns1 } from "./definitions/TpIslemCheckoutOdemeWns1";
import { TpIslemCheckoutOdemeWnsResponse1 } from "./definitions/TpIslemCheckoutOdemeWnsResponse1";
import { Sha2B641 } from "./definitions/Sha2B641";
import { Sha2B64Response1 } from "./definitions/Sha2B64Response1";
import { VadeliIslemIzleme1 } from "./definitions/VadeliIslemIzleme1";
import { VadeliIslemIzlemeResponse1 } from "./definitions/VadeliIslemIzlemeResponse1";
import { PazaryeriTpAltUyeIsyeriEkleme1 } from "./definitions/PazaryeriTpAltUyeIsyeriEkleme1";
import { PazaryeriTpAltUyeIsyeriEklemeResponse1 } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeResponse1";
import { PazaryeriTpAltUyeIsyeriEklemeV21 } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeV21";
import { PazaryeriTpAltUyeIsyeriEklemeV2Response1 } from "./definitions/PazaryeriTpAltUyeIsyeriEklemeV2Response1";
import { PazaryeriTpAltUyeIsyeriGuncelleme1 } from "./definitions/PazaryeriTpAltUyeIsyeriGuncelleme1";
import { PazaryeriTpAltUyeIsyeriGuncellemeResponse1 } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeResponse1";
import { PazaryeriTpAltUyeIsyeriGuncellemeV21 } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeV21";
import { PazaryeriTpAltUyeIsyeriGuncellemeV2Response1 } from "./definitions/PazaryeriTpAltUyeIsyeriGuncellemeV2Response1";
import { PazaryeriTpAltUyeIsyeriListe1 } from "./definitions/PazaryeriTpAltUyeIsyeriListe1";
import { PazaryeriTpAltUyeIsyeriListeResponse1 } from "./definitions/PazaryeriTpAltUyeIsyeriListeResponse1";
import { PazaryeriTpAltUyeIsyeriSilme1 } from "./definitions/PazaryeriTpAltUyeIsyeriSilme1";
import { PazaryeriTpAltUyeIsyeriSilmeResponse1 } from "./definitions/PazaryeriTpAltUyeIsyeriSilmeResponse1";
import { PazaryeriTpIptalIade1 } from "./definitions/PazaryeriTpIptalIade1";
import { PazaryeriTpIptalIadeResponse1 } from "./definitions/PazaryeriTpIptalIadeResponse1";
import { PazaryeriTpLimitKontrol1 } from "./definitions/PazaryeriTpLimitKontrol1";
import { PazaryeriTpLimitKontrolResponse1 } from "./definitions/PazaryeriTpLimitKontrolResponse1";
import { PazaryeriTpSiparisDetayEkle1 } from "./definitions/PazaryeriTpSiparisDetayEkle1";
import { PazaryeriTpSiparisDetayEkleResponse1 } from "./definitions/PazaryeriTpSiparisDetayEkleResponse1";
import { MpOrderDetailAdd1 } from "./definitions/MpOrderDetailAdd1";
import { MpOrderDetailAddResponse1 } from "./definitions/MpOrderDetailAddResponse1";
import { MpOrderDetailUpdate1 } from "./definitions/MpOrderDetailUpdate1";
import { MpOrderDetailUpdateResponse1 } from "./definitions/MpOrderDetailUpdateResponse1";
import { MpOrderDetailStatus1 } from "./definitions/MpOrderDetailStatus1";
import { MpOrderDetailStatusResponse1 } from "./definitions/MpOrderDetailStatusResponse1";
import { MpOrderDetailQuery1 } from "./definitions/MpOrderDetailQuery1";
import { MpOrderDetailQueryResponse1 } from "./definitions/MpOrderDetailQueryResponse1";
import { MpOrderRefund1 } from "./definitions/MpOrderRefund1";
import { MpOrderRefundResponse1 } from "./definitions/MpOrderRefundResponse1";
import { MpOrderDetailList1 } from "./definitions/MpOrderDetailList1";
import { MpOrderDetailListResponse1 } from "./definitions/MpOrderDetailListResponse1";
import { TpModalPayment1 } from "./definitions/TpModalPayment1";
import { TpModalPaymentResponse1 } from "./definitions/TpModalPaymentResponse1";
import { ParamPazaryeriIslemIzleme1 } from "./definitions/ParamPazaryeriIslemIzleme1";
import { ParamPazaryeriIslemIzlemeResponse1 } from "./definitions/ParamPazaryeriIslemIzlemeResponse1";
import { PazaryeriTpSiparisOnay1 } from "./definitions/PazaryeriTpSiparisOnay1";
import { PazaryeriTpSiparisOnayResponse1 } from "./definitions/PazaryeriTpSiparisOnayResponse1";
import { PazaryeriTpIslemSorgulama1 } from "./definitions/PazaryeriTpIslemSorgulama1";
import { PazaryeriTpIslemSorgulamaResponse1 } from "./definitions/PazaryeriTpIslemSorgulamaResponse1";
import { PosPluginBildirim1 } from "./definitions/PosPluginBildirim1";
import { PosPluginBildirimResponse1 } from "./definitions/PosPluginBildirimResponse1";
import { IlListe1 } from "./definitions/IlListe1";
import { IlListeResponse1 } from "./definitions/IlListeResponse1";
import { MoneyPayIslemSorgulama1 } from "./definitions/MoneyPayIslemSorgulama1";
import { MoneyPayIslemSorgulamaResponse1 } from "./definitions/MoneyPayIslemSorgulamaResponse1";
import { TurkPosX0020WsX0020Test } from "./services/TurkPosX0020WsX0020Test";
import {ITemp} from "../types";

export interface ServiceTurkposTestClient extends SoapClient {
    TurkPosX0020WsX0020Test: TurkPosX0020WsX0020Test;
    BIN_SanalPosAsync(binSanalPos: BinSanalPos): Promise<[result: BinSanalPosResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    BIN_SanalPos2Async(binSanalPos2: BinSanalPos2): Promise<[result: BinSanalPos2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_ListeAsync(tpOzelOranListe: TpOzelOranListe): Promise<[result: TpOzelOranListeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_SK_ListeAsync(tpOzelOranSkListe: TpOzelOranSkListe): Promise<[result: TpOzelOranSkListeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_SK_GuncelleAsync(tpOzelOranSkGuncelle: TpOzelOranSkGuncelle): Promise<[result: TpOzelOranSkGuncelleResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Dekont_GonderAsync(tpIslemDekontGonder: TpIslemDekontGonder): Promise<[result: TpIslemDekontGonderResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_OdemeAsync(tpIslemOdeme: TpIslemOdeme): Promise<[result: TpIslemOdemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_PayAsync(tpWmdPay: TpWmdPay): Promise<[result: TpWmdPayResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_v2Async(tpWmdUcdV2: TpWmdUcdV2): Promise<[result: TpWmdUcdV2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCDAsync(tpWmdUcd: TpWmdUcd): Promise<[result: TpWmdUcdResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_WPAsync(tpWmdUcdWp: TpWmdUcdWp): Promise<[result: TpWmdUcdWpResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_PuanAsync(tpWmdUcdPuan: TpWmdUcdPuan): Promise<[result: TpWmdUcdPuanResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Payment_HopiAsync(paymentHopi: PaymentHopi): Promise<[result: PaymentHopiResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Multiple_PaymentAsync(tpMultiplePayment: TpMultiplePayment): Promise<[result: TpMultiplePaymentResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Multiple_Payment_StatusAsync(tpMultiplePaymentStatus: TpMultiplePaymentStatus): Promise<[result: TpMultiplePaymentStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WNSAsync(tpIslemOdemeWns: TpIslemOdemeWns): Promise<[result: TpIslemOdemeWnsResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WDAsync(tpIslemOdemeWd: TpIslemOdemeWd): Promise<[result: TpIslemOdemeWdResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_BKMAsync(tpIslemOdemeBkm: TpIslemOdemeBkm): Promise<[result: TpIslemOdemeBkmResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WKSAsync(tpIslemOdemeWks: TpIslemOdemeWks): Promise<[result: TpIslemOdemeWksResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    KK_SaklamaAsync(kkSaklama: KkSaklama): Promise<[result: KkSaklamaResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    KK_Sakli_ListeAsync(kkSakliListe: KkSakliListe): Promise<[result: KkSakliListeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pos_OdemeAsync(posOdeme: PosOdeme): Promise<[result: PosOdemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_SorgulamaAsync(tpIslemSorgulama: TpIslemSorgulama): Promise<[result: TpIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama4Async(tpIslemSorgulama4: TpIslemSorgulama4): Promise<[result: TpIslemSorgulama4Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama5Async(tpIslemSorgulama5: TpIslemSorgulama5): Promise<[result: TpIslemSorgulama5Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama6Async(tpIslemSorgulama6: TpIslemSorgulama6): Promise<[result: TpIslemSorgulama6Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama_WPAsync(tpIslemSorgulamaWp: TpIslemSorgulamaWp): Promise<[result: TpIslemSorgulamaWpResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_DetayAsync(tpMutabakatDetay: TpMutabakatDetay): Promise<[result: TpMutabakatDetayResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_Detay2Async(tpMutabakatDetay2: TpMutabakatDetay2): Promise<[result: TpMutabakatDetay2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_OzetAsync(tpMutabakatOzet: TpMutabakatOzet): Promise<[result: TpMutabakatOzetResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_IadeAsync(tpIslemIptalIade: TpIslemIptalIade): Promise<[result: TpIslemIptalIadeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade2Async(tpIslemIptalIade2: TpIslemIptalIade2): Promise<[result: TpIslemIptalIade2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_IzlemeAsync(tpIslemIzleme: TpIslemIzleme): Promise<[result: TpIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_KismiAsync(tpIslemIptalIadeKismi: TpIslemIptalIadeKismi): Promise<[result: TpIslemIptalIadeKismiResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi2Async(tpIslemIptalIadeKismi2: TpIslemIptalIadeKismi2): Promise<[result: TpIslemIptalIadeKismi2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi3Async(tpIslemIptalIadeKismi3: TpIslemIptalIadeKismi3): Promise<[result: TpIslemIptalIadeKismi3Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi4Async(tpIslemIptalIadeKismi4: TpIslemIptalIadeKismi4): Promise<[result: TpIslemIptalIadeKismi4Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi_WPAsync(tpIslemIptalIadeKismiWp: TpIslemIptalIadeKismiWp): Promise<[result: TpIslemIptalIadeKismiWpResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_OnProvAsync(tpIslemIptalOnProv: TpIslemIptalOnProv): Promise<[result: TpIslemIptalOnProvResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_KK_VerifyAsync(tpKkVerify: TpKkVerify): Promise<[result: TpKkVerifyResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_KapaAsync(tpIslemOdemeOnProvKapa: TpIslemOdemeOnProvKapa): Promise<[result: TpIslemOdemeOnProvKapaResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProvAsync(tpIslemOdemeOnProv: TpIslemOdemeOnProv): Promise<[result: TpIslemOdemeOnProvResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_WMDAsync(tpIslemOdemeOnProvWmd: TpIslemOdemeOnProvWmd): Promise<[result: TpIslemOdemeOnProvWmdResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_WKSAsync(tpIslemOdemeOnProvWks: TpIslemOdemeOnProvWks): Promise<[result: TpIslemOdemeOnProvWksResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Checkout_SKAsync(tpIslemCheckoutSk: TpIslemCheckoutSk): Promise<[result: TpIslemCheckoutSkResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_CheckoutAsync(tpIslemCheckout: TpIslemCheckout): Promise<[result: TpIslemCheckoutResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Checkout_Odeme_WNSAsync(tpIslemCheckoutOdemeWns: TpIslemCheckoutOdemeWns): Promise<[result: TpIslemCheckoutOdemeWnsResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    SHA2B64Async(sha2B64: Sha2B64): Promise<[result: Sha2B64Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Vadeli_Islem_IzlemeAsync(vadeliIslemIzleme: VadeliIslemIzleme): Promise<[result: VadeliIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_EklemeAsync(pazaryeriTpAltUyeIsyeriEkleme: PazaryeriTpAltUyeIsyeriEkleme): Promise<[result: PazaryeriTpAltUyeIsyeriEklemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme_v2Async(pazaryeriTpAltUyeIsyeriEklemeV2: PazaryeriTpAltUyeIsyeriEklemeV2): Promise<[result: PazaryeriTpAltUyeIsyeriEklemeV2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_GuncellemeAsync(pazaryeriTpAltUyeIsyeriGuncelleme: PazaryeriTpAltUyeIsyeriGuncelleme): Promise<[result: PazaryeriTpAltUyeIsyeriGuncellemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme_v2Async(pazaryeriTpAltUyeIsyeriGuncellemeV2: PazaryeriTpAltUyeIsyeriGuncellemeV2): Promise<[result: PazaryeriTpAltUyeIsyeriGuncellemeV2Response, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_ListeAsync(pazaryeriTpAltUyeIsyeriListe: PazaryeriTpAltUyeIsyeriListe): Promise<[result: PazaryeriTpAltUyeIsyeriListeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_SilmeAsync(pazaryeriTpAltUyeIsyeriSilme: PazaryeriTpAltUyeIsyeriSilme): Promise<[result: PazaryeriTpAltUyeIsyeriSilmeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Iptal_IadeAsync(pazaryeriTpIptalIade: PazaryeriTpIptalIade): Promise<[result: PazaryeriTpIptalIadeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Limit_KontrolAsync(pazaryeriTpLimitKontrol: PazaryeriTpLimitKontrol): Promise<[result: PazaryeriTpLimitKontrolResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Siparis_Detay_EkleAsync(pazaryeriTpSiparisDetayEkle: PazaryeriTpSiparisDetayEkle): Promise<[result: PazaryeriTpSiparisDetayEkleResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailAddAsync(mpOrderDetailAdd: MpOrderDetailAdd): Promise<[result: MpOrderDetailAddResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailUpdateAsync(mpOrderDetailUpdate: MpOrderDetailUpdate): Promise<[result: MpOrderDetailUpdateResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailStatusAsync(mpOrderDetailStatus: MpOrderDetailStatus): Promise<[result: MpOrderDetailStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailQueryAsync(mpOrderDetailQuery: MpOrderDetailQuery): Promise<[result: MpOrderDetailQueryResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderRefundAsync(mpOrderRefund: MpOrderRefund): Promise<[result: MpOrderRefundResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailListAsync(mpOrderDetailList: MpOrderDetailList): Promise<[result: MpOrderDetailListResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Modal_PaymentAsync(tpModalPayment: TpModalPayment): Promise<[result: TpModalPaymentResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Param_Pazaryeri_Islem_IzlemeAsync(paramPazaryeriIslemIzleme: ParamPazaryeriIslemIzleme): Promise<[result: ParamPazaryeriIslemIzlemeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Siparis_OnayAsync(pazaryeriTpSiparisOnay: PazaryeriTpSiparisOnay): Promise<[result: PazaryeriTpSiparisOnayResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Islem_SorgulamaAsync(pazaryeriTpIslemSorgulama: PazaryeriTpIslemSorgulama): Promise<[result: PazaryeriTpIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pos_Plugin_BildirimAsync(posPluginBildirim: PosPluginBildirim): Promise<[result: PosPluginBildirimResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Il_ListeAsync(ilListe: IlListe): Promise<[result: IlListeResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MoneyPay_Islem_SorgulamaAsync(moneyPayIslemSorgulama: MoneyPayIslemSorgulama): Promise<[result: MoneyPayIslemSorgulamaResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    BIN_SanalPosAsync(binSanalPos: BinSanalPos1): Promise<[result: BinSanalPosResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    BIN_SanalPos2Async(binSanalPos2: BinSanalPos21): Promise<[result: BinSanalPos2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_ListeAsync(tpOzelOranListe: TpOzelOranListe1): Promise<[result: TpOzelOranListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_SK_ListeAsync(tpOzelOranSkListe: TpOzelOranSkListe1): Promise<[result: TpOzelOranSkListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Ozel_Oran_SK_GuncelleAsync(tpOzelOranSkGuncelle: TpOzelOranSkGuncelle1): Promise<[result: TpOzelOranSkGuncelleResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Dekont_GonderAsync(tpIslemDekontGonder: TpIslemDekontGonder1): Promise<[result: TpIslemDekontGonderResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_OdemeAsync(tpIslemOdeme: TpIslemOdeme1): Promise<[result: TpIslemOdemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_PayAsync(tpWmdPay: TpWmdPay1): Promise<[result: TpWmdPayResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_v2Async(tpWmdUcdV2: TpWmdUcdV21): Promise<[result: TpWmdUcdV2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCDAsync(tpWmdUcd: TpWmdUcd1): Promise<[result: TpWmdUcdResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_WPAsync(tpWmdUcdWp: TpWmdUcdWp1): Promise<[result: TpWmdUcdWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCD_PuanAsync(tpWmdUcdPuan: TpWmdUcdPuan1): Promise<[result: TpWmdUcdPuanResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Payment_HopiAsync(paymentHopi: PaymentHopi1): Promise<[result: PaymentHopiResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Multiple_PaymentAsync(tpMultiplePayment: TpMultiplePayment1): Promise<[result: TpMultiplePaymentResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Multiple_Payment_StatusAsync(tpMultiplePaymentStatus: TpMultiplePaymentStatus1): Promise<[result: TpMultiplePaymentStatusResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WNSAsync(tpIslemOdemeWns: TpIslemOdemeWns1): Promise<[result: TpIslemOdemeWnsResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WDAsync(tpIslemOdemeWd: TpIslemOdemeWd1): Promise<[result: TpIslemOdemeWdResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_BKMAsync(tpIslemOdemeBkm: TpIslemOdemeBkm1): Promise<[result: TpIslemOdemeBkmResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WKSAsync(tpIslemOdemeWks: TpIslemOdemeWks1): Promise<[result: TpIslemOdemeWksResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    KK_SaklamaAsync(kkSaklama: KkSaklama1): Promise<[result: KkSaklamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    KK_Sakli_ListeAsync(kkSakliListe: KkSakliListe1): Promise<[result: KkSakliListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pos_OdemeAsync(posOdeme: PosOdeme1): Promise<[result: PosOdemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_SorgulamaAsync(tpIslemSorgulama: TpIslemSorgulama1): Promise<[result: TpIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama4Async(tpIslemSorgulama4: TpIslemSorgulama41): Promise<[result: TpIslemSorgulama4Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama5Async(tpIslemSorgulama5: TpIslemSorgulama51): Promise<[result: TpIslemSorgulama5Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama6Async(tpIslemSorgulama6: TpIslemSorgulama61): Promise<[result: TpIslemSorgulama6Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Sorgulama_WPAsync(tpIslemSorgulamaWp: TpIslemSorgulamaWp1): Promise<[result: TpIslemSorgulamaWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_DetayAsync(tpMutabakatDetay: TpMutabakatDetay1): Promise<[result: TpMutabakatDetayResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_Detay2Async(tpMutabakatDetay2: TpMutabakatDetay21): Promise<[result: TpMutabakatDetay2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Mutabakat_OzetAsync(tpMutabakatOzet: TpMutabakatOzet1): Promise<[result: TpMutabakatOzetResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_IadeAsync(tpIslemIptalIade: TpIslemIptalIade1): Promise<[result: TpIslemIptalIadeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade2Async(tpIslemIptalIade2: TpIslemIptalIade21): Promise<[result: TpIslemIptalIade2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_IzlemeAsync(tpIslemIzleme: TpIslemIzleme1): Promise<[result: TpIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_KismiAsync(tpIslemIptalIadeKismi: TpIslemIptalIadeKismi1): Promise<[result: TpIslemIptalIadeKismiResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi2Async(tpIslemIptalIadeKismi2: TpIslemIptalIadeKismi21): Promise<[result: TpIslemIptalIadeKismi2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi3Async(tpIslemIptalIadeKismi3: TpIslemIptalIadeKismi31): Promise<[result: TpIslemIptalIadeKismi3Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi4Async(tpIslemIptalIadeKismi4: TpIslemIptalIadeKismi41): Promise<[result: TpIslemIptalIadeKismi4Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_Iade_Kismi_WPAsync(tpIslemIptalIadeKismiWp: TpIslemIptalIadeKismiWp1): Promise<[result: TpIslemIptalIadeKismiWpResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Iptal_OnProvAsync(tpIslemIptalOnProv: TpIslemIptalOnProv1): Promise<[result: TpIslemIptalOnProvResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_KK_VerifyAsync(tpKkVerify: TpKkVerify1): Promise<[result: TpKkVerifyResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_KapaAsync(tpIslemOdemeOnProvKapa: TpIslemOdemeOnProvKapa1): Promise<[result: TpIslemOdemeOnProvKapaResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProvAsync(tpIslemOdemeOnProv: TpIslemOdemeOnProv1): Promise<[result: TpIslemOdemeOnProvResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_WMDAsync(tpIslemOdemeOnProvWmd: TpIslemOdemeOnProvWmd1): Promise<[result: TpIslemOdemeOnProvWmdResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_OnProv_WKSAsync(tpIslemOdemeOnProvWks: TpIslemOdemeOnProvWks1): Promise<[result: TpIslemOdemeOnProvWksResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Checkout_SKAsync(tpIslemCheckoutSk: TpIslemCheckoutSk1): Promise<[result: TpIslemCheckoutSkResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_CheckoutAsync(tpIslemCheckout: TpIslemCheckout1): Promise<[result: TpIslemCheckoutResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Checkout_Odeme_WNSAsync(tpIslemCheckoutOdemeWns: TpIslemCheckoutOdemeWns1): Promise<[result: TpIslemCheckoutOdemeWnsResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    SHA2B64Async(sha2B64: Sha2B641): Promise<[result: Sha2B64Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Vadeli_Islem_IzlemeAsync(vadeliIslemIzleme: VadeliIslemIzleme1): Promise<[result: VadeliIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_EklemeAsync(pazaryeriTpAltUyeIsyeriEkleme: PazaryeriTpAltUyeIsyeriEkleme1): Promise<[result: PazaryeriTpAltUyeIsyeriEklemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_Ekleme_v2Async(pazaryeriTpAltUyeIsyeriEklemeV2: PazaryeriTpAltUyeIsyeriEklemeV21): Promise<[result: PazaryeriTpAltUyeIsyeriEklemeV2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_GuncellemeAsync(pazaryeriTpAltUyeIsyeriGuncelleme: PazaryeriTpAltUyeIsyeriGuncelleme1): Promise<[result: PazaryeriTpAltUyeIsyeriGuncellemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_Guncelleme_v2Async(pazaryeriTpAltUyeIsyeriGuncellemeV2: PazaryeriTpAltUyeIsyeriGuncellemeV21): Promise<[result: PazaryeriTpAltUyeIsyeriGuncellemeV2Response1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_ListeAsync(pazaryeriTpAltUyeIsyeriListe: PazaryeriTpAltUyeIsyeriListe1): Promise<[result: PazaryeriTpAltUyeIsyeriListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_AltUyeIsyeri_SilmeAsync(pazaryeriTpAltUyeIsyeriSilme: PazaryeriTpAltUyeIsyeriSilme1): Promise<[result: PazaryeriTpAltUyeIsyeriSilmeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Iptal_IadeAsync(pazaryeriTpIptalIade: PazaryeriTpIptalIade1): Promise<[result: PazaryeriTpIptalIadeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Limit_KontrolAsync(pazaryeriTpLimitKontrol: PazaryeriTpLimitKontrol1): Promise<[result: PazaryeriTpLimitKontrolResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Siparis_Detay_EkleAsync(pazaryeriTpSiparisDetayEkle: PazaryeriTpSiparisDetayEkle1): Promise<[result: PazaryeriTpSiparisDetayEkleResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailAddAsync(mpOrderDetailAdd: MpOrderDetailAdd1): Promise<[result: MpOrderDetailAddResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailUpdateAsync(mpOrderDetailUpdate: MpOrderDetailUpdate1): Promise<[result: MpOrderDetailUpdateResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailStatusAsync(mpOrderDetailStatus: MpOrderDetailStatus1): Promise<[result: MpOrderDetailStatusResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailQueryAsync(mpOrderDetailQuery: MpOrderDetailQuery1): Promise<[result: MpOrderDetailQueryResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderRefundAsync(mpOrderRefund: MpOrderRefund1): Promise<[result: MpOrderRefundResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MP_OrderDetailListAsync(mpOrderDetailList: MpOrderDetailList1): Promise<[result: MpOrderDetailListResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Modal_PaymentAsync(tpModalPayment: TpModalPayment1): Promise<[result: TpModalPaymentResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Param_Pazaryeri_Islem_IzlemeAsync(paramPazaryeriIslemIzleme: ParamPazaryeriIslemIzleme1): Promise<[result: ParamPazaryeriIslemIzlemeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Siparis_OnayAsync(pazaryeriTpSiparisOnay: PazaryeriTpSiparisOnay1): Promise<[result: PazaryeriTpSiparisOnayResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pazaryeri_TP_Islem_SorgulamaAsync(pazaryeriTpIslemSorgulama: PazaryeriTpIslemSorgulama1): Promise<[result: PazaryeriTpIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Pos_Plugin_BildirimAsync(posPluginBildirim: PosPluginBildirim1): Promise<[result: PosPluginBildirimResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    Il_ListeAsync(ilListe: IlListe1): Promise<[result: IlListeResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
    MoneyPay_Islem_SorgulamaAsync(moneyPayIslemSorgulama: MoneyPayIslemSorgulama1): Promise<[result: MoneyPayIslemSorgulamaResponse1, rawResponse: any, soapHeader: any, rawRequest: any]>;
}

export interface ServiceTurkposClient extends ServiceTurkposTestClient , ServiceTurkposClientImpl{

}

export interface ServiceTurkposClientImpl {
    BIN_SanalPosAsyncImpl(binSanalPos: BinSanalPos): Promise<[result: ITemp , rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_WMD_UCDAsyncImpl(tpWmdUcd: TpWmdUcd): Promise<[result: TpWmdUcdResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
    TP_Islem_Odeme_WDAsyncImpl(tpIslemOdemeWd: TpIslemOdemeWd): Promise<[result: TpIslemOdemeWdResponse, rawResponse: any, soapHeader: any, rawRequest: any]>;
}
/** Create ServiceTurkposTestClient */
export function createClientAsync(...args: Parameters<typeof soapCreateClientAsync>): Promise<ServiceTurkposClient> {
    return soapCreateClientAsync(args[0], args[1], args[2]) as any;
}
